# Generated by Django 3.2.8 on 2021-10-13 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setlist_tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='type',
            new_name='link_type',
        ),
    ]
